#!/bin/bash

read -d '' usage << "BLOCK"
VERSION: 1.0
RELEASE DATE: Thu Apr 20 2017 
AUTHOR: Suman Guha

DESCRIPTION: 
Finds and converts all .h264 files into .mp4 for all epochs in an animal's folder

DEPENDECIES: 
Requires ffmpeg to be installed 

USAGE: convertH264ToMp4 <ARGUMENT>

INPUT FLAGS: --help | -h

EXAMPLE: convertH264ToMp4 $(pwd)	
BLOCK

# Converting flags from long form to short form
for arg in $@; do
	shift
	case $arg in
		--help) 	set -- $@ -h;;
		*)		set -- $@ $arg;;
	esac
done

# Setting parameters according to flags
while getopts h	flags; 
do
	case $flags in
		h)	echo "$usage"; exit 1;;
	esac
done

convertFunc ()
{
	cd $1
	for f in $(ls *.h264); do
		ffmpeg -i $f $(echo $f | sed 's/.h264//').mp4
	done
}

for d in $(ls -d $1/*/); do
	convertFunc $d &
done
wait
