#!/usr/bin/env bash

# Helper section
# --------------
read -d '' usage << "BLOCK"
DESCRIPTION:

USAGE:

INPUT FLAGS:

EXAMPLE:

VERSION: 1.0
RELEASE DATE: Wed Nov 07 2017
AUTHOR: Suman Guha
BLOCK

# Input section
# -------------

# Converting flags from long form to short form
for opt in $@; do
	shift
	case $opt in
		--help) 	set -- $@ -h;;
		--file)		set -- $@ -f;;
		*)		set -- $@ $opt;;
	esac
done

# Setting parameters according to flags
while getopts "hf:" opt; do
	case $opt in
		h) echo "$usage"; exit 0;;
		f) fileName=$OPTARG;;
	esac
done

# Algorithm and main function:
# ----------------------------

# 1. Parse individual subject/animal record into its separate file
# ----------------------------------------------------------------

# 1.1 Generate array of start and end line numbers for each animal
# Generate line numbers where records start for individual animal --> Records for individual animals are separated by "Start Date:" and the last line of the whole file gives the end of the last record
endLine=$(wc -l < $fileName)
endLine=$(( $endLine + 1 )) # adding one to total line numbers because later the end is set as endLine - 1
lineNums=($(awk '/Start\ Date:/ {print FNR}' $fileName) $endLine)

# 1.2. Generate and array(s) meta-data variables
date="$(awk 'BEGIN {FS="!"} NR==1 {print $2}' $fileName)" #fist line of the day file has the date in the desired format and is preceded by ! which is used as a record separator
subjectList=($(awk '/Subject:/ {print $2}' $fileName)) #second record seems to be the name of the animals while the first record acts as the identifying pattern
experimentList=($(awk '/Experiment: / {print $2}' $fileName))
groupList=($(awk '/Group: / {print $2}' $fileName))

# <Debug Section: Uncomment to see debug info on console>
# -------------------------------------------------------
#echo ${lineNums[@]}
#echo $date
#echo ${subjectList[@]}
#echo ${experimentList[@]}
#echo ${groupList[@]}

# 2. Process individual subject/animal record
# -------------------------------------------

# 2.1. Splice and save individual animal record in .tmp files
# -----------------------------------------------------------
subjectNums=$(( ${#subjectList[@]} - 1 ))
for i in $(seq 0 $subjectNums)
do
	tmpFile=$(echo $date"_"${experimentList[i]}"_"${groupList[i]}"_"${subjectList[$i]}.tmp)
	startLine=${lineNums[$i]}
	endLine=${lineNums[(( $i + 1 ))]}
	endLine=$(( $endLine - 1 ))
	sed -n "${startLine}, ${endLine}p" $fileName > $tmpFile

	#<Debug Section>
	#echo $tmpFile
	#read -n 1
	#echo ${lineNums[$i]}
	#echo ${lineNums[(( $i + 1 ))]}
	#echo $startLine $endLine
	#read -n 1
done
