#!/bin/bash

read -d '' usage << "BLOCK"
VERSION: 1.0
RELEASE DATE: Wed Nov 07 2017 
AUTHOR: Suman Guha

DESCRIPTION: This script crawls through an animal directory containing .trodesComments files of a day. Interleaves sleep and run epochs per day and prints out the trodesComments files in that specific order for verfication 

USAGE: viewTrodesComments -FLAGS|--LONG_NAME_OF_FLAGS <ARGUMENTS>

INPUT FLAGS:
--dayDir	: The folder for the animal where all epochs for the day are stored
--sleepSession	: Snippet of the sleep epoch (character sensitive). E.g., Sleep
--runSession	: Snippet of the run epoch (character sensitive). E.g., Odor, W-Track 

EXAMPLE:	
If in directory of animal (CS31), where the Run and Sleep epochs are named 

CS31_20170201_OdorPlace_01.rec
CS31_20170201_OdorPlace_02.rec

and ... 

CS31_20170201_Sleep_01.rec
CS31_20170201_Sleep_02.rec
CS31_20170201_Sleep_03.rec

then run: viewTrodesComments --dayDir $(pwd) --sleepSession Sleep --runSession Odor 

BLOCK

# Converting flags from long form to short form
for opt in $@; do
	shift
	case $opt in
		--dayDir) 	set -- $@ -d;;
		--sleepSession)	set -- $@ -s;;
		--runSession)	set -- $@ -r;;
		--help) 	set -- $@ -h;;
		*)		set -- $@ $opt;;
	esac
done

# Setting parameters according to flags

while getopts "hd:s:r:" opt; do
	case $opt in
		h) echo "$usage"; exit 0;;
		d) dayDir=$OPTARG;;
		s) sleepSession=$OPTARG;;
		r) runSession=$OPTARG;;
	esac
done

currDir=$(pwd);
cd $dayDir;
sleepSessionList=($(ls *$sleepSession*.trodesComments | sort));
runSessionList=($(ls *$runSession*.trodesComments | sort));
sleepSessionNum=$(echo ${#sleepSessionList[@]});
runSessionNum=$(echo ${#runSessionList[@]});

for i in $(seq 0 $(( $sleepSessionNum - 1 ))); do
    echo ${sleepSessionList[i]};
    cat ${sleepSessionList[i]};
    if [ $i -le $(( ${#runSessionList[@]} - 1 )) ]; then
        echo ${runSessionList[i]};
        cat ${runSessionList[i]};
    fi
done

cd $currDir;
