#! /usr/bin/env Rscript

# 0. HELPER AND INPUT SECTION
# ---------------------------

# Loading libraries
# -----------------
library(argparser, quietly = TRUE)

# Creating a parser
# -----------------
p <- arg_parser(
  "DESCRIPTION:"
)

# Add command line arguments
# --------------------------
p <- add_argument(p, "dateRange", help="range of dates", type="character") # primary argument(s)
#p <- add_argument(p, "-- ", help=" [ ]", type="character", default=" ") # optional argument(s)
# Parse command line arguments
# ----------------------------
argv <- parse_args(p)

# 1. MAIN SECTION
# ---------------
print(argv)
